In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('MLfinal.csv')
df

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,...,WT04,WT04_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT06,WT06_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES
0,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2017-01-01,9.84,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2017-01-02,10.07,",,W",NaN,NaN,...,1.0,",,W",NaN,NaN,NaN,NaN,1.0,",,W",NaN,NaN
2,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2017-01-03,13.42,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2017-01-04,17.67,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2017-01-05,17.67,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2276,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2023-03-27,11.63,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2277,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2023-03-28,8.95,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2278,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2023-03-29,12.97,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2279,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2023-03-30,15.21,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2280,USW00094789,"JFK INTERNATIONAL AIRPORT, NY US",40.63915,-73.7639,2.7,2023-03-31,9.62,",,W",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN